token: hereYourToken
shardsTotal: 5
imgurClientId: imgurClientId
googleAnalyticsId: analyticsTrackingId
mysqlDatabase: dbName
mysqlPassword: dbPass
mysqlUrl: dbUrl
mysqlUser: dbUser
mysqlPort: dbPort
igdbApiKey: igbd.com api key
discordBotListApiToken:
restUser:
restPassword:
lavaPlayerNodeUrl:
# used for yt-ip-rotator, not active if null
ipv6Block:
